program Pecube324

! program to transform old Pecube input files (topo_parameters.txt and fault_parameters.f90)
! into new Pecube input file format (Pecube.in)

implicit none

integer i,j,k,nstep,nfault,n
character line*1024,ci*10,ck*10

open (54,file='old_input/topo_parameters.txt',status='old')
open (55,status='scratch')
1 read (54,'(a1024)',end=2) line
  if (line(1:1).ne.'$'.and. line(1:1).ne.' ') then
    if (scan(line,'$').ne.0) then
      do i=scan(line,'$'),1024
      line(i:i)=' '
      enddo
    endif

  k=1
    do j=1,1024
      if (line(j:j).eq.' '.or.line(j:j).eq.',') then
      if (j.ne.k) write (55,'(a)') line(k:j-1)
      k=j+1
      endif
    enddo
  endif

goto 1

2 close (54)
rewind (55)

! run is the name of the run (assumes a directory of that name exists)
! should be 5 character long
read (55,'(a1024)') line

call system ('mkdir -p '//trim(line))
call system ('mkdir -p '//trim(line)//'/input')
open (77,file=trim(line)//'/input/Pecube.in',status='unknown')

write (77,'(a)') 'Pecube.in file generated by Pecube324'

write (77,'(a)') ''
write (77,'(a)') 'Topographic information'

! fnme is the name of the input topographic file
! nfnme is the length of the file name
read (55,'(a)') line
write (77,'(a," = ",a)') 'topo_file_name',trim(line)

! nx0 and ny0 are the number of points in the input topographic file
! dx and dy are the data spacings in the x- and y-direction in the input topographic
! file (in degrees)
! nskip is the number of points that are skipped when sampling the initial
! topo file
! xlat and xlon are the latitude/longitude of the bottom left corner of the
! data set (in deg.)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'nx',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'ny',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'dlon',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'dlat',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'nskip',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'lon0',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'lat0',trim(line)

write (77,'(a)') ''
write (77,'(a)') 'Topographic time evolution information'

! nstep is the number of time step
! tau is the erosion time scale (assuming an exponential decvrease in topography) (in Myr)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'ntime',trim(line)
read (line,*) nstep
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'erosional_time_scale',trim(line)

! for each time step + 1
! timek is the time (in Myr)
! topomag is the topographic amplification factor at this step
! topooffset is the topographic offset
do i=1,nstep+1
write (ci,'(i10)') i
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'time_topo'//trim(adjustl(ci)),trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'amplification'//trim(adjustl(ci)),trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'offset'//trim(adjustl(ci)),trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'output'//trim(adjustl(ci)),trim(line)
enddo

write (77,'(a)') ''
write (77,'(a)') 'Isostasy information'

! isostasy flag (0 no isostasy, 1 isostasy on)
! rhoc and rhom are the densities for the crust and mantle, respectively (in kg/m3)
! these values are used in the isostatic calculations
! young is the elastic plate young modulus (in Pa)
! poisson is poisson's ratio (dimensionless)
! thickness is the elastic thickness of the plate (in km)
! nxiso and nyiso are the resolutions in the x- and y-directions of the grid on
! which the isostatic (flexural) calculations are performed (including the FFT)
! note that these numbers must be powers of two.
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'isostasy',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'rho_crust',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'rho_asthenosphere',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'young_modulus',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'poisson_ratio',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'EET',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'nx_isostasy',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'ny_isostasy',trim(line)

write (77,'(a)') ''
write (77,'(a)') 'Thermal information'

! crustal thickness is the averaged crustal thickness (i.e. the depth at which the
! temperature is assumed to be constant) (in km)
! nz is the number of points in the z-direction
! diffusivity is the heat diffusivity (in km2/Myr)
! tmax is the basal temperature (in C)
! tmsl is the temperature at the top of the model (at z=0)
! tlapse is the lapse rate (or change of temperature with height in the atmosphere)
! (in C/km)
! heatproduction is the rate of heat production (in C/Myr)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'thickness',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'nz',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'thermal_diffusivity',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'basal_temperature',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'sea_level_temperature',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'lapse_rate',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'heat_production',trim(line)

write (77,'(a)') ''
write (77,'(a)') 'Data information'

! obsfile is the name of the observation file
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'data_folder',trim(line)

write (77,'(a)') ''
write (77,'(a)') 'Various flags'

! new parameters added in Pecube2

read (55,'(a1024)',end=999) line
write (77,'(a," = ",a)') 'default_age',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'T_code_flag',trim(line)

read (55,'(a1024)') line
write (77,'(a," = ",a)') 'misfit_slope',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'fault_advect_flag',trim(line)

read (55,'(a1024)') line
write (77,'(a," = ",a)') 'shear_heating',trim(line)

read (55,'(a1024)') line
write (77,'(a," = ",a)') 'age_AHe_flag',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'age_ZHe_flag',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'age_AFT_flag',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'age_ZFT_flag',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'age_KAr_flag',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'age_BAr_flag',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'age_MAr_flag',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'age_HAr_flag',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'age_FTL_flag',trim(line)

999  close (55)

! fault file

open (76,file='old_input/fault_parameters.txt',status='old')
open (55,status='scratch')
3 read (76,'(a1024)',end=4) line
  if (line(1:1).ne.'$'.and. line(1:1).ne.' ') then
    if (scan(line,'$').ne.0) then
      do i=scan(line,'$'),1024
      line(i:i)=' '
      enddo
    endif
  k=1
    do j=1,1024
      if (line(j:j).eq.' '.or.line(j:j).eq.',') then
      if (j.ne.k) write (55,'(a)') line(k:j-1)
      k=j+1
      endif
    enddo
  endif
goto 3
4 close (76)
rewind (55)

write (77,'(a)') ''
write (77,'(a)') 'Faulting information'

! nfault and geometry of trace of fault in lat-lon coordinates
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'nfault',trim(line)
read (line,*) nfault
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'lon1',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'lat1',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'lon2',trim(line)
read (55,'(a1024)') line
write (77,'(a," = ",a)') 'lat2',trim(line)

! for each fault
  do i=1,nfault
  write (ci,'(i10)') i
  write (77,'(a)') 'Fault'//ci

  write (77,'(a)') 'Geometry'
! fault geometry
read (55,'(a1024)') line
  write (77,'(a," = ",a)') 'npoint'//trim(adjustl(ci)),trim(line)
  read (line,*) n
! uniform uplift
    if (n.lt.0) then
    read (55,'(a1024)') line
    write (77,'(a," = ",a)') 'bottom_left',trim(line)
    read (55,'(a1024)') line
    write (77,'(a," = ",a)') 'bottom_right',trim(line)
    read (55,'(a1024)') line
    write (77,'(a," = ",a)') 'upper_right',trim(line)
    read (55,'(a1024)') line
    write (77,'(a," = ",a)') 'upper_left',trim(line)
! real fault geometry
    else
      do k=1,n
      write (ck,'(i10)') k
      read (55,'(a1024)') line
      write (77,'(a," = ",a)') 'r'//trim(adjustl(ci))//'_'//trim(adjustl(ck)),trim(line)
      read (55,'(a1024)') line
      write (77,'(a," = ",a)') 's'//trim(adjustl(ci))//'_'//trim(adjustl(ck)),trim(line)
      enddo
    endif

  write (77,'(a)') 'Time scenario'
! number of time steps
  read (55,'(a1024)') line
  read (line,*) nstep
  write (77,'(a," = ",a)') 'nstep'//trim(adjustl(ci)),trim(line)
! begining, end times and magnitude of velocity per time step
    do k=1,nstep
    write (ck,'(i10)') k
    read (55,'(a1024)') line
    write (77,'(a," = ",a)') 'time_start'//trim(adjustl(ci))//'_'//trim(adjustl(ck)),trim(line)
    read (55,'(a1024)') line
    write (77,'(a," = ",a)') 'time_end'//trim(adjustl(ci))//'_'//trim(adjustl(ck)),trim(line)
    read (55,'(a1024)') line
    write (77,'(a," = ",a)') 'velo'//trim(adjustl(ci))//'_'//trim(adjustl(ck)),trim(line)
    enddo

  enddo

close (55)



close (77)

end program Pecube324
